spring-cloud/spring-cloud-openfeign

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/CachingSpringLoadBalancerFactory.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonClientAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/CachingSpringLoadBalancerFactoryTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignRibbonClientTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancerTests.java
See spring-cloud/spring-cloud-commons#331
=> Refactor Spring Retry Code

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingInterceptor.java
Explaining the return in case of an exception.
To get to the return at the end of the method is only for this case. 
Thus avoiding an ignored exception.
=> Explaining the return in case of exception.

spring-cloud-openfeign-core/pom.xml, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringEncoderTests.java, spring-cloud-openfeign-dependencies/pom.xml
Proposed solution for https://github.com/spring-cloud/spring-cloud-openfeign/issues/62
The solution is based on
```
<dependency>
<groupId>io.github.openfeign.form</groupId>
<artifactId>feign-form-spring</artifactId>
<version>3.3.0</version>
</dependency>
```
Class `feign.form.spring.SpringFormEncoder` was added inside `org.springframework.cloud.openfeign.support.SpringEncoder` because it's doesn't has some checks:
1. Check of  `bodyType` on null.
`org.springframework.cloud.openfeign.support.SpringEncoder#encode` don't handle situation when `bodyType` is null.
2. No check for content type `multipart/form-data` in header. 
`feign.form.FormEncoder` requires `multipart/form-data` in header for proper processing.
All this checks added and tests are passed.
=> Added support for MultipartFile

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/CachingSpringLoadBalancerFactory.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/FeignLoadBalancer.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/ribbon/FeignLoadBalancerTests.java
Support to override CachingSpringLoadBalancerFactory to customize the FeignLoadBalancer instance.
use example:
```
@Configuration
public class FeignClientConfiguration {
@Bean
@Primary
public Client feignClient(SpringClientFactory clientFactory, @Autowired(required = false) LoadBalancedRetryFactory retryFactory) {
return new LoadBalancerFeignClient(new Client.Default(null, null),
new CustomCachingSpringLoadBalancerFactory(clientFactory, retryFactory), clientFactory);
}
class CustomCachingSpringLoadBalancerFactory extends CachingSpringLoadBalancerFactory {
private volatile Map<String, FeignLoadBalancer> cache = new ConcurrentReferenceHashMap<>();
public CustomCachingSpringLoadBalancerFactory(SpringClientFactory factory) {
super(factory);
}
public …
```
=> Support to set loadBalancerKey

spring-cloud-openfeign-dependencies/pom.xml
The earlier versions are not compatible with Feign 10.1.0 when using the
form encoder.
Fixes #105
=> Upgrade feign-form to 3.5.0

spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringEncoderTests.java
More assertions for multipart tests with `SpringEncoder`
Fixes gh-107
=> Fixes gh-107

2.0.x/ghpages.sh, 2.1.x/ghpages.sh, ghpages.sh
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch with 3 occurrences migrated to:  
https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch ([https](https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch) result 200).
* http://stackoverflow.com/questions/29300806/a-bash-script-to-check-if-a-string-is-present-in-a-com …
=> URL Cleanup

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientOverrideDefaultsTests.java
Added the possibility to override the default QueryMapEncoder by defining a custom one in the ApplicationContext.
=> Overridable QueryMapEncoder

docs/src/main/asciidoc/spring-cloud-openfeign.adoc
This addresses the ambiguity around whether to provide a Bean of feign.okhttp.OkHttpClient or okhttp3.OkHttpClient
=> Docs: Fully qualify names for HTTP client beans

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java
Hi,
in the current version the FeignClientBuilder.Builder is return always it's raw type and not the generic one. This leads to many unckeck cast warnings or type mismatch errors.
With the current version the following code, will produce an type mismatch error
```
@Bean
public DummyClass dummyClass() {
return feignClientBuilder.forType(DummyClass.class, "dummyClass")
.url("URL").build();
}
//Error:(25, 57) java: incompatible types: java.lang.Object cannot be converted to DummyClass
```
The problem is, that the method url is returning **Builder** instead of **Builder&lt;T&gt;**. 
I also changed the parameter for the two methods fallback & fallbackFactory to **Class&lt;?&gt;** (as mention in #184), so the code is backward-compatible. Also the BuilderTest will set the fallback to Object. …
=> FeignClientBuilder.Builder should always return the generic builder

.circleci/config.yml
Attempted fix for: "execution not authorized due to: free-plan-resource-class-unavailable"
https://circleci.com/gh/spring-cloud/spring-cloud-openfeign/1225?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Switch to medium resource class in circleci.

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/DefaultGzipDecoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/DefaultGzipDecoderTests.java
Problem Statement:
- When tested with a UTF-8, DefaultGzipDecoder returned with garbage data because it is using latin-1 charsets.
- The added test case in the PR proves such case.
Suggestion:
- [SpringEncoder.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/1ce5ca1ba83a96036efa105d1fedfb1a72f0303f/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java#L136) uses UTF-8 by default  So it makes sense to use UTF-8 when decoding.
=> Changing DefaultGzipDecoder's charset to UTF-8

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClient.java
Referring to <code>@Configuration</code> is a bit confusing. The referred class does not need the annotation, and actually using it could cause issues due the class additionally getting picked up by the component scan.
=> Update Javadoc for FeignClient.configuration()

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientOverrideDefaultsTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java, spring-cloud-openfeign-core/src/test/resources/feign-properties.properties
Can be configured via properties or as a `@Bean`.
Fixes GH-243
=> Support for configuring the ExceptionPropagationPolicy

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
Keep default ```AnnotatedParameterProcessor```s while defining custom ones.
Fixes gh-111
=> Define custom AnnotatedParameterProcessor while keeping defaults

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/annotation/RequestPartParameterProcessor.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringEncoder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringEncoderTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/valid/FeignClientTests.java
Summary of changes follows:
- Delegate ALL requestBody encoding where `Content-Type` is `multipart/form-data` to the `SpringFormEncoder`.
- Introduce `RequestPartParameterProcessor` to deal with `@RequestPart` annotations, adds parameters to `MethodMetadata.formParams()`.
- Wrap `HttpMessageConversionException` in `EncodeException`.
- Add tests to verify expected behaviour.
However there still exists a gap in functionality where any user defined pojo will be serialized as a `Map<String,String>`, as there is currently no way for `SpringFormEncoder` to know about the `Content-Type` of the individual parts beyond `MultipartFile`, boxed primitive types (which are treated as `text/plain`) and other built-in types inherited from `FormEncoder`.
=> Fix GH-201: Multiple @RequestPart not Working

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClient.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/DefaultFeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/FeignBlockingLoadBalancerClient.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/FeignLoadBalancerAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/HttpClientFeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/OkHttpFeignLoadBalancerConfiguration.java, src/checkstyle/checkstyle-suppressions.xml
IMPORTANT: Only merge after: https://github.com/spring-cloud/spring-cloud-commons/pull/691is merged.
=> Adjust to ribbon changes in commons

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignErrorDecoderFactory.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientErrorDecoderTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignErrorDecoderFactoryTests.java
this factory will be used if no ErrorDecoder was found. This factory allows to create a ErrorDecoder based on the type. This fixes #308
=> add support for an FeignErrorDecoderFactory in 2.2.x

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageJacksonModule.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageJacksonModuleTests.java
=> Use property 'number' in JSON Page representation instead of 'page'

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignBuilderCustomizer.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignBuilderCustomizerTests.java
Adds a ```Customizer``` for ```Feign.Builder``` to allow customization. 
When used ```FeignBuilderCustomizer``` will override other configurations.
Effects ```@FeignClient``` and ```FeignClientBuilder``` building.
fixes gh-244
=> add customizer for feign builder

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/Targeter.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java
Exposed ```Targeter``` and ```FeignClientFactoryBean``` to public.
I did not add ```@Autowired``` to ```FeignClientFactoryBean``` in ```FeignClientBuilder.Builder``` as suggested in gh-278. I had some concerns that there may be some side effects from that since the builder is expecting a new instance each time. Instead I overloaded ```FeignClientBuilder.forType()``` so a instance of ```FeignClientFactoryBean``` could be provided when needed.
fixes gh-278
fixes gh-240
=> exposed client factory bean and targeter

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/CollectionFormat.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableSupportTest.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
=> Add CollectionFormat support

docs/src/main/asciidoc/spring-cloud-openfeign.adoc
This should fix https://github.com/spring-cloud/spring-cloud-openfeign/issues/391
I have created a whole new section as long as I believe the timeout handling configuration is something almost always to be customized by developers. 
Please review it. I am open to leave it as is, move it as a part of another section or create a subsection of an existing one.
=> Fixes gh-391 timeout handling documentation

spring-cloud-openfeign-core/pom.xml, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/security/OAuth2FeignRequestInterceptor.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/MockAccessTokenProvider.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/MockOAuth2AccessToken.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/MockOAuth2ClientContext.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/OAuth2FeignRequestInterceptorTests.java, spring-cloud-openfeign-dependencies/pom.xml
- moved the interceptor
- added configuration for the interceptor
Maybe @dsyer or @spencergibb will remember why there was no auto configuration for the oauth2 interceptor for Feign in the first place? I couldn't find one in Spring Cloud Security.
fixes #444
=> Moved the code from Spring Cloud Security

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingConfigurerTest.java
without this change we're eagerly resolving placeholder properties in passed URLs / names. Since this happens at bean definition level it's extremely early e.g. Spring Cloud Contract has not yet registered any placeholders that Feign could try to consume.
with this change we're changing the bean to become lazy initialized and we resolve the placeholder values at runtime - as late as possible.
problems:
- one of the tests uses the factory bean - there's no more factory bean since the instance supplier for the bean registration acts as one
related issue https://github.com/spring-cloud/spring-cloud-contract/issues/1303
=> Lazy openfeign bean registration

spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
#430 haven't added configuration metadata for `feign.autoconfiguration.jackson.enabled`, so I added it.
I've seen #470, so `defaultValue` can be changed by next major release.
=> Add configuration metadata for feign.autoconfiguration.jackson.enabled

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java
I've modified https://github.com/spring-cloud/spring-cloud-openfeign/blob/faff6aef8acdf2367c1b5596a384cbe86e1200c5/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java as suggested in #440 along with corresponding tests.
https://github.com/spring-cloud/spring-cloud-openfeign/blob/faff6aef8acdf2367c1b5596a384cbe86e1200c5/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java#L119
If you run tests which I add without the patch of `PageSpringEncoder.java` and you'll be able to see the test fails.
=> Encode Pageable.Sort with percent encoded comma. Fixes gh-440.

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/HystrixDisabledConditions.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignAutoConfigurationTests.java
Changes:
- Removed `@ConditionalOnMissingClass(HystrixFeign, CircuitBreaker)` on `DefaultFeignTargeterConfiguration`. Both classes are present by default and this causes the DefaultTargeter not to be considered even if Hystrix and CircuitBreaker are disabled.
- Position `DefaultTargeter` behind `HystrixTargeter` using `@AutoConfigureAfter`
- Position `HystrixTargeter` behind `CircuitBreakerTarger` using `@AutoConfigureAfter`
- Make it possible to disable `HystrixTargeter` by setting `feign.hystrix.enabled` to `false`. Keep default behaviour from previous release where  `HystrixTargeter` was the default (`matchIfMissing`).
- Only enable `CircuitBreakerTargeter` if `feign.circuitbreaker.enabled` is true
=> Fixes #482 No bean found of type Targeter.

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/app/client/InvoiceClient.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/app/resource/InvoiceResource.java
Based on https://github.com/spring-cloud/spring-cloud-openfeign/issues/440#issuecomment-776979189, also see #385
I've implemented `PageableSpringQueryMapEncoder` which processes `Pageable`, `Sort` which annotated as `@SpringQueryMap` to use with `@RequestBody`, along with tests.
Usage:
```java
@RequestMapping(value = "invoicesPagedWithBody", method = RequestMethod.POST,
consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
ResponseEntity<Page<Invoice>> getInvoicesPagedWithBody(
@SpringQueryMap org.springframework.data.domain.Pageable pageable, @RequestBody String titlePrefix);
```
I think I should make PR to branch 2.2.x also, so please notify me if needed.
=> Support Pageable, Sort annotated as SpringQueryMap to use with RequestBody

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/AsyncCircuitBreaker.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/AsyncCircuitBreakerTest.java
If we introduce circuit breaker (Resilience4JCircuitBreaker) module, our `feign.SynchronousMethodHandler` will be executed by `org.springframework.cloud.circuitbreaker.resilience4j.Resilience4JCircuitBreaker` asynchronously, so that our `feign.RequestInterceptor`s could not access `request context`. 
This PR tries to fix #193 and other similar cases like headers proxy.
=> Expose request attributes for circuit breaker async invocation

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientBuilder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignBuilderCustomizerTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java
=> Add FeignClientBuilder.Builder#customize(FeignBuilderCustomizer) (#499)

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java
'url' is never null in given case. At least I think so. Even if I'm wrong there is no need to distinguish between null and empty. Goal is simple: Inform reader that feign is created with load-balancer, not with url.
=> Simplify Log.info logic

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/CircuitBreakerNameResolver.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreaker.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerTargeter.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignAutoConfigurationTests.java
fixes gh-574
This PR includes an extension point for changing circuit breaker name.
`3.0.2` version included some change for a circuit breaker name. And this caused change of circuit breaker metric names.
CircuitBreakerNameResolver can be used for a developer to give own circuit breaker name.
=> Add CircuitBreakerNameResolver

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableEncoderWithSpringDataWebTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoderTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoderWithSpringDataWebTests.java
`PageableSpringQueryMapEncoder` should use parameter names from `SpringDataWebProperties` if customized as well as `PageableSpringEncoder`
=> Respect SpringDataWebProperties where possible

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageJacksonModule.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/PageJacksonModuleTests.java
As discussed here https://github.com/spring-cloud/spring-cloud-openfeign/pull/636#discussion_r773598943
@KENNYSOFT @OlgaMaciaszek Please review.
=> Fix cascading deserialization Spring Data's Page by setting @JsonIgnoreProperties(ignoreUnknown = true)

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientFactoryBean.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignBuilderCustomizerTests.java
The call of applyBuildCustomizers has been done before applying the HttpClient from FeignContext.
This PR moves the call at the end of the getTarget Method. It will allow to use a custom HttpClient. See #671 for more details.
Follow Up PR for #672 (rebased on 3.1.x branch)
Move Call of ```applyBuildCustomizers()``` at end of ```getTarget()``` method.
Add Unit Test to verify custom HttpClients are set.
Modify Unit Tests to use ```getTarget()``` method instead of ```feign()``` method. ```feign()``` method has protected access and is only used within test scope. All other access happens through ```getTarget()``` method
fixes gh-671
=> Allow to inject custom HttpClient to programmatically created FeignClients

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/DefaultFeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/FeignBlockingLoadBalancerClient.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/HttpClient5FeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/HttpClientFeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/LoadBalancerFeignRequestTransformer.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/OkHttpFeignLoadBalancerConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/RetryableFeignBlockingLoadBalancerClient.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/loadbalancer/FeignBlockingLoadBalancerClientTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/loadbalancer/RetryableFeignBlockingLoadBalancerClientTests.java
Applications can define their own LoadBalancerFeignRequestTransformer beans
which can modify the Request to be executed. These beans can be
@Ordered in case of multiple transformers.
reference [Transform the load-balanced HTTP request]( https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#transform-the-load-balanced-http-request)
=> Customize load balanced requests according to the chosen ServiceInstance

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/FeignLoadBalancerAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/loadbalancer/XForwardedHeadersTransformer.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/loadbalancer/XForwardedHeadersTransformerTests.java
`spring.cloud.loadbalancer.x-forwarded.enabled=true` to Enable X-Forwarded Headers.
=> Enable X-Forwarded Headers.

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/circuitbreaker/AsyncCircuitBreakerTest.java
Fixes #716
Make `FeignCircuitBreakerInvocationHandler#asSupplier` compare the calling thread and the executing thread for consistency before the operation, use `ThreadLocal` to pass request attributes in the asynchronous call, and do nothing in the synchronous call.
=> Release RequestAttributes when called asynchronously. Fixes gh-716

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/AbstractFormWriter.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTests.java
Fixes #741
Make `AbstractFormWriter#isTypeOrCollection()` handle byte[] arrays correctly instead of casting byte[] to object[] directly.
=> Handle byte[] arrays correctly.(Fixes gh-741)

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignOkHttpConfigurationTests.java
We no longer need the abstraction in commons and will be removing it
=> Use OK HttpClient directly

docs/src/main/asciidoc/_configprops.adoc, docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientMicrometerEnabledCondition.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java, spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientConfigurationTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientDisabledClientLevelFeaturesTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientDisabledFeaturesTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientMicrometerEnabledConditionTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientOverrideDefaultsTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingConfigurerTest.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientUsingPropertiesTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientsMicrometerAutoConfigurationTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/GzipDecodingTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/MicrometerPropertiesTests.java, spring-cloud-openfeign-core/src/test/resources/application.yml
This change auto-configures `MicrometerObservationCapability`. The previous auto-configuration for `MicrometerCapability` is still available but for that `MicrometerObservationCapability` should not be present (disabled, no observation registry, micrometer-observation is not on the classpath).
**Breaking change:** properties were renamed from `spring.cloud.openfeign.metrics` to `spring.cloud.openfeign.micrometer`.
Previous Micrometer support in SC-OpenFeign: https://github.com/spring-cloud/spring-cloud-openfeign/pull/462
`MicrometerObservationCapability` support in Feign: https://github.com/OpenFeign/feign/pull/1760
=> Micrometer Observation API Support

docs/src/main/asciidoc/spring-cloud-openfeign.adoc
1. Remove LoadBalancerFeignRequestTransformer
LoadBalancerFeignRequestTransformer is not merged into 3.1. X
2. Fix configuration properties format errors
[spring-cloud-openfeign/docs/current](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#transform-the-load-balanced-http-request)
=> LoadBalancerFeignRequestTransformer document description error

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/FeignHttpClientProperties.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/FeignHttpClientPropertiesTests.java
Fixes issue [Can't config connection request timeout for http client #799](https://github.com/spring-cloud/spring-cloud-openfeign/issues/799) for 3.1.x
=> connectionRequestTimeout for httpClient Fixes gh-799

docs/src/main/asciidoc/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignCircuitBreakerInvocationHandler.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignAcceptGzipEncodingAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/FeignContentGzipEncodingAutoConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/encoding/OkHttpFeignClientBeanMissingCondition.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignCompressionTests.java
Fixes gh-725. 
A bean-based condition is not a good solution in this scenario as the FeignClientFactoryBean is affecting autoconfiguration processing order - the interceptors are being resolved before the actual client bean, so the condition is evaluated too early.
=> Fix condition.

docs/modules/ROOT/pages/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignHttpClient5ConfigurationTests.java
Hi, Olga.
I always thank for your efforts.
I would like to provide the ability for a user to customize settings, In addition to leveraging existing Spring Cloud settings.
In the previous version, ApacheHttpClientFactory interface existed. So I could customize HttpClientBuilder additionally.
But, in the current version, there is no method for HttpClientBuilder configurations.
Thank you!
=> Add HttpClientBuilderCustomizer interface

docs/modules/ROOT/pages/spring-cloud-openfeign.adoc
=> (docs): Replace `@RequestMapping` with newer `@GetMapping` (etc.)

docs/modules/ROOT/partials/_configprops.adoc, spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
This pr fixes typo in description of the configuration property `spring.cloud.openfeign.circuitbreaker.group.enabled`.
Thanks.
=> Fix simple typo on Configuration Properties page

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/ResponseEntityDecoder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringDecoder.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/SpringDecoderIntegrationTests.java
=> Add support for custom HTTP status codes

docs/modules/ROOT/pages/spring-cloud-openfeign.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
Previously, SpringMvcContract did not support parsing the `params` parameter of `@RequestMapping`.
Example:
1. Define a rest interface that uses the `params` parameter：
```
@PutMapping(value = "/user", params = "action=disable")
public String disableUser() {
return "user";
}
```
2. Define a FeignClient to call the previously declared interface：
```
@FeignClient("user-server")
static interface UserService {
@PutMapping(value = "/user", params = "action=disable")
String disableUser();
}
```
When sending this request, the request path will be resolved to `/user` instead of `/user?action=disable`, resulting in 400 errors.
Therefore, this PR provides the ability to parse `params` parameter.
=> SpringMvcContract support parse params

spring-cloud-openfeign-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
defaultValue of `spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled` is `true` since version 4.0.0
=> fix: defaultValue in additional-spring-configuration-metadata.json

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/security/OAuth2AccessTokenInterceptor.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/security/OAuth2AccessTokenInterceptorTests.java
The authorizedClientManager.authorize method requires a non-null principal name or it will usually throw an exception in practice like "principalName cannot be empty".
Using the anonymous principal in this case like for a null principal handles the situation more gracefully.
Fixes #1049
=> Authorize with anonymous principal if principal name is null

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringEncoder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageableSpringQueryMapEncoder.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SortJsonComponent.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/encoding/FeignPageableEncodingTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SortJacksonModuleTests.java
Adds ignorecase field to pageable spring for compatibility with SortHandlerMethodArgumentResolverSupport::parseIgnoreCase
=> Adds ignorecase field to pageable spring

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java
```getName (Map<String, Object>)``` does not need to be for test purposes.
=> polishing FeignClientsRegistrar

docs/modules/ROOT/pages/spring-cloud-openfeign.adoc, docs/modules/ROOT/partials/_configprops.adoc, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientProperties.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java, spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientBuilderTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/FeignClientsRegistrarTests.java, spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/SpringMvcContractTests.java
=> Allow removing trailing slashes

spring-cloud-openfeign-core/pom.xml, spring-cloud-openfeign-dependencies/pom.xml
This PR backports #1103 to the 4.1.x branch.
=> fix #1102: feign-form-spring relocated under io.github.openfeign (backport #1103)

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/SpringQueryMap.java
When using the `@SpringQueryMap` annotation, it was difficult to discover the existence of the `QueryMapEncoder` class.  
The reference path is as follows:  
`@SpringQueryMap -> @QueryMap -> @Param Usage All`
Additionally, when using `@SpringQueryMap`, the default injected implementation is `FieldQueryMapEncoder`.  
However, in `FeignClientsConfiguration`, the injected bean can change depending on the `@ConditionalOnClass` condition.
```java
@Bean
@ConditionalOnClass(name = "org.springframework.data.domain.Pageable")
@ConditionalOnMissingBean
public QueryMapEncoder feignQueryMapEncoderPageable() {
PageableSpringQueryMapEncoder queryMapEncoder = new PageableSpringQueryMapEncoder();
if (springDataWebProperties != null) {
queryMapEncoder.setPageParameter(springDataWebProperties.getPageable(). …
```
=> docs: Improve SpringQueryMap documentation

spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/SpringMvcContract.java
This PR addresses issue [#1191](https://github.com/spring-cloud/spring-cloud-openfeign/issues/1191) by adding a warning when a `@FeignClient` method is declared as `GET` but has one or more parameters that are **not annotated** with any supported HTTP binding annotations (e.g., `@RequestParam`, `@RequestHeader`, `@PathVariable`, `@SpringQueryMap`, etc.).
When no annotations are present, Feign may attempt to treat those parameters as a request body. For `GET` methods, this leads to a body-less `POST` due to underlying HTTP client behavior (e.g., `HttpURLConnection`), which causes a discrepancy:
- The client logs show the request as `GET`
- The server receives the request as a `POST`
- No request body is actually sent (`Content-Length: 0`)
This is difficult to debug and confusing in …
=> feat: warn when GET method has unannotated parameters
